---
commands:
  postgres: deploy-postgresql-service
  logme: deploy-logme-service
  mysql: deploy-mysql-service
  redis: deploy-redis-service
  harbor: deploy-harbor-service
  mongodb: deploy-mongodb-service
  messaging: deploy-rabbitmq-service
  kubernetes: deploy-kubernetes-service
  prometheus: deploy-prometheus-service
  elasticsearch: deploy-elasticsearch-service
